name: Playwrigth Tests
on: [push]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:next
      env:
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chrome
          npx playwright install msedge

      - name: Run tests
        run: |
          chmod +x './ShoppingStoreApp/shopping-store-linux-amd64'
            ./ShoppingStoreApp/shopping-store-linux-amd64 &
          npm run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Allure results
          path: allure-results/
          retention-days: 30
